CREATE TABLE [dbo].[CustomerTypes](
	[Code] [int] IDENTITY(1,1) NOT NULL,
	[Type] [char](20) NOT NULL,
 CONSTRAINT [PK_tiposclientes] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]